### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.10 and pinning 2018.07.24

### PR DESCRIPTION
**Pull request by ocefpaf**
Add py37.

### CODE REVIEW

**Comment by jochym** [comment]
@ocefpaf something seems to be wrong with CCI jobs for this PR. See: https://circleci.com/gh/ocefpaf/pyqt-feedstock/28
https://circleci.com/gh/ocefpaf/pyqt-feedstock/27
https://circleci.com/gh/ocefpaf/pyqt-feedstock/26
They run for 4 hours just waiting on password line. Please cancel them - they are blocking the queue.

**Comment by jschueller** [comment]
Did you add py37 manually ?

**Comment by ocefpaf** [comment]
> Did you add py37 manually ?

Yep. Global Python 3.7 with the bot is coming soon,
but if you want to manually convert a few you can edit
your `miniconda3/conda_build_config.yaml` file and add `3.7` there.
Then all you need to do is a re-render.

Note that you need to duplicate the `vs2015` keys and the `vc 14` key.

**Comment by jschueller** [comment]
ok, thanks

**Pull request merged**
