### PR TITLE
Update 5.6.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Second round  of #13 

Closes https://github.com/conda-forge/pyqt-feedstock/issues/1

### CODE REVIEW

**Comment by ocefpaf** [comment]
Python 2.7 is failing with (see https://ci.appveyor.com/project/conda-forge/pyqt-feedstock/build/1.0.41/job/vao3bnn2m2hg2bso):

```
Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 322, in main
    execute(sys.argv[1:])
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 313, in execute
    noverify=args.no_verify)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1494, in build_tree
    config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1013, in build
    create_env(config.build_prefix, specs, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 689, in create_env
    execute_actions(actions, index, verbose=config.debug)
  File "C:\Miniconda-x64\lib\site-packages\conda\plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda-x64\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda-x64\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "C:\Miniconda-x64\lib\site-packages\conda\install.py", line 1009, in link
    if not run_script(prefix, dist, 'post-link'):
  File "C:\Miniconda-x64\lib\site-packages\conda\install.py", line 500, in run_script
    subprocess.check_call(args, env=env)
  File "C:\Miniconda-x64\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Miniconda-x64\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Miniconda-x64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Miniconda-x64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

OS X is at the limit. Sometimes it passes and sometimes it doesn't :unamused:

**Comment by ccordoba12** [comment]
It seems an error in `conda`, when running Qt's post link script.

**Comment by ocefpaf** [comment]
> It seems an error in `conda`, when running Qt's post link script.

I will see  if I can get OS X to pass and merge this regardless. I'll open an issue to keep track of that error.

**Comment by ccordoba12** [comment]
I restarted Travis to see if it passes this time.

**Comment by jakirkham** [comment]
> Python 2.7 is failing with (see https://ci.appveyor.com/project/conda-forge/pyqt-feedstock/build/1.0.41/job/vao3bnn2m2hg2bso)

That error looks kind of like issue ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/60 ), but in a different context.

**Comment by ocefpaf** [comment]
@ccordoba12 let's get this in. I will monitor `Windows` and `OS X` re-starts on `master`.

**Comment by ccordoba12** [comment]
:+1: thanks for taking the time to make this happen!!

**Comment by jakirkham** [comment]
Raised the AppVeyor failure in issue ( https://github.com/conda/conda-build/issues/1853 ).

**Comment by ocefpaf** [comment]
Thanks @ccordoba12 for the help with the recipe!

**Pull request merged**
