### PR TITLE
Add PyQt 5.7 wheels binaries

### PR DESCRIPTION
**Pull request by hadim**
Qt 5.7 is unlikely to appear anytime soon in `conda-forge`. In the meantime could we use the wheels binaries available in PyPi for PyQt 5.7 ?

(only for py35)

@conda-forge-admin

### CODE REVIEW

**Comment by ccordoba12** [comment]
I completely disagree with this PR. My reasons:

1. We can compile binaries from scratch. Conda-forge maintainers agreed to allow certain individuals to create packages and upload them to anaconda.org. For now this is going to start with Qt4, but I hope it'll continue with Qt5 in short time.
2. PyQt5 wheels have several problems, e.g. spyder-ide/spyder#3520. This is because they are using WebEngine (based on Chromium) as its default web backend. In Continuum we preferred to use WebKit, which is still more stable.
3. You're not creating a new branch for this change but instead replacing `master` contents. That's not the way to proceed.

----

Please allow us (the feedstock maintainers) to do these changes. I know it's frustrating to still not have Qt5/PyQt5 in conda-forge, but it'll arrive, just be patient :-)

**Comment by ccordoba12** [comment]
I cancelled the build because of my reasons above. This simply is not going in, sorry.

**Comment by hadim** [comment]
Just trying to help and move forward...

**Comment by ccordoba12** [comment]
Sorry, I understand that :-) After Qt4 packages for conda-forge are all in place, @mingwandroid, @ocefpaf and me will continue with Qt5.

**Comment by hadim** [comment]
Yes and this PR was just a temporary way to have PyQt 5.7 waiting for a more appropriate solution.

Anyway.

**Comment by hadim** [comment]
For the second point, there is a lot of projects not using WebEngine/WebKit so once again as a temporary package, this PR is ok.

For the third point, that is easy to fix....

**Comment by hadim** [comment]
Anyway I give up trying to help here...

**Comment by ccordoba12** [comment]
@hadim, this is not the right solution, that's all, sorry.

**Comment by ocefpaf** [comment]
@hadim a more consistent solution will be implemented soon. I am traveling
this week but I plan to upload qt builds as soon possible.

Also, conda-forge is changing its policy regarding repackaging stuff. More
on this soon.

BTW your help is valuable, stick around 😉 But the discussion is important
too. So have patience and I assure you a better solution will be in place
soon.

**Comment by hadim** [comment]
@ccordoba12 this is not the correct way to answer, that's all sorry.

@ocefpaf I didn't know about repackaging policy. I can understand that and will wait for a more consistent solution then.

**Comment by ccordoba12** [comment]
> @ccordoba12 this is not the correct way to answer, that's all sorry.

I don't know what you mean :-/

What I tried to say is that we're not considering your work valuable, just that this PR is not the correct way to address the update to PyQt5 (for the reasons i explained above).

**Comment by ocefpaf** [comment]
> @ccordoba12 this is not the correct way to answer, that's all sorry.

Let's not worry too much. Short and incomplete answers happens.

> @ocefpaf I didn't know about repackaging policy. I can understand that
and will wait for a more consistent solution then.

No one knows ; -) We are still discussing that. But the goal is to reduce
repackaging as much as possible.

**Pull request closed without merging**
