### PR TITLE
Update to 5.6.0

### PR DESCRIPTION
**Pull request by ocefpaf**
First cut of the `pyqt 5.6.x` version. I don't expect this to pass on `Windows` nor `OS X`. Hopefully this will play nice with the `qt 5` package from https://github.com/conda-forge/qt-feedstock/pull/24

### CODE REVIEW

**Comment by ocefpaf** [comment]
Linux is failing with:

```shell
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/recipe_root_1485184107182/_t_env
+ /feedstock_root/build_artefacts/recipe_root_1485184107182/_t_env/bin/python -s /feedstock_root/build_artefacts/recipe_root_1485184107182/test_tmp/run_test.py
===== testing package: pyqt-5.6.0-py27_0 =====
import: 'PyQt5.QtCore'
running run_test.py
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
```


@mingwandroid and @ccordoba12 does that sounds familiar? Did I miss any `yum` dependency in https://github.com/conda-forge/qt-feedstock/pull/24 ?

**Comment by hadim** [comment]
That might be relevant : http://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

**Comment by ocefpaf** [comment]
Thanks for the info!

The builds take such a long time on my old laptop that it is quite
discouraging to perform any tests :-(

I  will be out for a while but I'll try to fix Qt5/pyqt once I get back.

On Feb 10, 2017 6:53 PM, "Hadrien Mary" <notifications@github.com> wrote:

That might be relevant : http://stackoverflow.com/
questions/17106315/failed-to-load-platform-plugin-xcb-
while-launching-qt5-app-on-linux-without

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/pyqt-feedstock/pull/13#issuecomment-279076530>,
or mute the thread

**Comment by hadim** [comment]
On my system when I skip the test and install the generated package in a conda env, PyQt5 works fine. I think there is a problem with `qt.conf` or `QT_PLUGIN_PATH` in the env created during the `conda build` command.

Maybe someone with more experience with the way `conda build` works have an idea of what is going on ?

**Comment by ccordoba12** [comment]
I have an idea on how to fix this, but it requires a rebuild of Qt 5. I'll try to do it this week :-)

**Comment by hadim** [comment]
Maybe adding `Plugins = /opt/anaconda1anaconda2anaconda3/plugins` to https://github.com/conda-forge/qt-feedstock/blob/master/recipe/qt.conf would help.

**Comment by ocefpaf** [comment]
> I have an idea on how to fix this, but it requires a rebuild of Qt 5. I'll try to do it this week :-)

@ccordoba12 if you don't have time please let me know your ideas. I am all out! (I re-build qt5 +15 today with different combinations and nothing worked :unamused:)

**Comment by ccordoba12** [comment]
@ocefpaf, I think the solution is to run run `ldd` on `plugins/platforms/libqxcb.so` (from the Qt package) and install all X libraries needed by that one in `yum_requirements.txt` here for the test to pass.

Or make a simpler test, i.e. a test that doesn't require an X server installed.

**Comment by ccordoba12** [comment]
The test for the Qt package doesn't require an X server, for example.

**Comment by ocefpaf** [comment]
> I think the solution is to run run `ldd` on `plugins/platforms/libqxcb.so` (from the Qt package) and install all X libraries needed by that one in `yum_requirements.txt` here for the test to pass.

I was trying that but maybe I missed one... I will try again.

> The test for the Qt package doesn't require an X server, for example.

If that is an option maybe we should just do that.

**Comment by ocefpaf** [comment]
I will re-submit this one once  builds successfully.

**Pull request closed without merging**
