### PR TITLE
Rebuild with new conda-build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I thought this would be an easy one, but something is going wrong. I observed that the Windows SDK tools version shown in the linker error doesn't match the one set earlier in the build - not sure why though:
```
LINK : fatal error LNK1181: cannot open input file 'C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64\shell32.lib'
```
&
```
(base) D:\bld\pyqt_split_1610322824354\work>if errorlevel 1 (echo "Didn't find any windows 10 SDK. I'm not sure if things will work, but let's try..." )  else (echo Windows SDK version found as: "10.0.17763.0" ) 
Windows SDK version found as: "10.0.17763.0"
```

**Comment by ocefpaf** [comment]
Thanks for the PR, we really need a rebuild of pyqt that "works." But I believe that @isuruf found a problem with this conda-build release and we probably need to wait a bit more. Maybe the problem you are seeing here is unrelated though.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Should be fixed with the latest qt rebuild.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please restart ci

**Comment by isuruf** [comment]
@Tobias-Fischer, why restart CI, when it was already green? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=261531&view=results

**Comment by Tobias-Fischer** [comment]
I wasn't sure whether the last QT version was pulled in - sorry for that.

**Comment by Tobias-Fischer** [comment]
Seems like indeed all builds fine. I think this is ready to be merged @conda-forge/pyqt

**Comment by gillins** [comment]
Thanks @Tobias-Fischer !

**Comment by ocefpaf** [comment]
Thanks for fixing this!

**Pull request merged**
