### PR TITLE
FIX: Properly set pyshlib suffix.

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

After merging #54 I noticed that the plugins started to look for `libpythonX.Ym.a.PREFIX` in which X is the major version, Y is minor and PREFIX is `.so` for Linux and `.dylib` for OSX. E.g. `libpython3.7m.a.so`.

This new PR forces the proper suffix since the one that we fetch from sysconfig provides the wrong shared library name.

Attn. @isuruf

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
Just a little more context...
If I run the code from `configure.py` using a anaconda python, I get the proper library prefix but during the CI build process it is not true, which caused the confusion and mistake.

**Comment by hhslepicka** [comment]
@isuruf @ccordoba12 this is good for a review. Sorry about the mistake and the need to open a new PR to still tackle this problem with the plugin.

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
