### PR TITLE
Add aarch64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/arm-arch @conda-forge/pyqt - what is the best way to deal with this? Some of the builds finished in time, and the other ones just didn't make it. Hope for the best that when merging the server is less busy? Or build on the conda-forge server?

**Comment by hmaarrfk** [comment]
i think merge. then monitor on master to rebuild until it works.

You can also try to build on azure

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Thanks @hmaarrfk - good point re building on Azure, let's try this :)

**Comment by Tobias-Fischer** [comment]
It took a long time but it works. It would be great if this PR could be merged @conda-forge/pyqt @conda-forge/arm-arch :)

**Comment by Tobias-Fischer** [comment]
Ping @conda-forge/pyqt

**Comment by gillins** [comment]
@Tobias-Fischer I can't seem to find `aarch64` packages for `pyqt` - did they ever get built in the end?

**Comment by Tobias-Fischer** [comment]
For some reason the build wasn't triggered .. what is the best way to deal with that @conda-forge/pyqt @wolfv?

**Comment by wolfv** [comment]
weird. I can see green ticks for the aarch64 configuration. Maybe pushing an empty commit to master?

**Comment by Tobias-Fischer** [comment]
@conda-forge/pyqt - could someone please do an empty commit on master?

**Comment by gillins** [comment]
Done. Let's see what happens...

**Comment by Tobias-Fischer** [comment]
Great, that did the trick :)

**Pull request merged**
